config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resource :tweets

  root to: 'application#index'

  get '/timeline', to: 'tweets#index', as: :user_root
  get '/timeline/follow/:id', to: 'tweets#follow', as: :timeline_follow_user
  get '/timeline/unfollow/:id', to: 'tweets#unfollow', as: :timeline_unfollow_user

  get '/user/follow/:id', to: 'users#follow', as: :user_follow
  get '/user/unfollow/:id', to: 'users#unfollow', as: :user_unfollow


  get '/tweets/search', to:'tweets#search', as: :tweets_search
  get '/users/search', to:'users#search', as: :users_search

  resources :users, only: :show do
    resources :relations, only: :index
  end
end

app/models/mention.rb
class Mention < ActiveRecord::Base
  belongs_to :tweet
  belongs_to :user
end

app/models/relation.rb
class Relation < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates_presence_of :follower_id
  validates_presence_of :followed_id
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  validates_presence_of :content
  validates :content, length: {minimum: 1, maximum: 141 }

  def find_mentions
    scan_for_mentions.each { |user| user.mentions << Mention.new(tweet_id: id) }
  end

private

  def scan_for_mentions
    content.scan(/@[\w]{4,12}\b/).map { |m| User.find_by(handle: m[/\w{4,12}/]) }.compact.uniq
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise  :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :handle
  validates_uniqueness_of :handle
  validates :handle, length: { minimum: 4, maximum: 12 }
  validates :handle, format: { with: /\w+/ }
  validates :bio, length: { maximum: 141 }
  validates_with AttachmentSizeValidator, :attributes => :avatar, :less_than => 1.megabytes

  has_attached_file :avatar,
                    :styles => { :thumb => "64x64", :medium => "300x300>",
                                  :large => "600x600>" },
                    :default_url => 'unknown.png'

  validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/jpeg", "image/gif", "image/png"]

  has_many :relations, foreign_key: 'follower_id', dependent: :destroy
  has_many :followed_users, through: :relations, source: :followed

  has_many  :reverse_relations, foreign_key: 'followed_id',
            class_name: 'Relation', dependent: :destroy
  has_many :followers, through: :reverse_relations
  has_many :tweets
  has_many :mentions

  def follow!(another_user)
    relations.create!(followed_id: another_user.id)
  end

  def following?(another_user)
    relations.find_by(followed_id: another_user.id)
  end

  def unfollow!(another_user)
    relations.find_by(followed_id: another_user.id).destroy
  end

  def all_tweets
    ( (followed_users.map { |user| user.tweets.all } ).flatten + tweets)
  end

  def all_tweets_timeline
    all_tweets.sort { |a, b| a.created_at > b.created_at ? -1 : 1 }
  end

  def any_tweets?
    all_tweets.any?
  end

  def mentioned?(tweet)
    mentions.find_by(user_id: id, tweet_id: tweet.id) == nil ? false : true
  end

private

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def index
    redirect_to user_root_path if user_signed_in?
  end

private

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :handle
    # maybe .flatten?
    devise_parameter_sanitizer.for(:account_update) << [:bio, :avatar, :handle]
  end

end

app/controllers/relations_controller.rb
class RelationsController < ApplicationController

  def index
    @user = User.find(params[:user_id])
  end


end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, :only => [:create, :destroy, :follow, :unfollow]
  before_action :build_timeline, :only => [:index, :create]

  def index
      @tweet = Tweet.new
      @user = current_user

      redirect_to new_user_session_path unless user_signed_in?
  end

  def create
    @tweet = Tweet.new(tweet_params)

    if @tweet.save
      @tweet.find_mentions
      respond_to do |format|
        format.js
        format.html { redirect_to user_root_path }
      end
    else
        render('index')
    end
  end

  def search
    @search_term = params[:search_term]
    @tweets = Tweet.basic_search(@search_term)
  end

  def follow
    @user = User.find(params[:id])
    current_user.follow!(@user)

    respond_to do |format|
      format.js
      format.html { redirect_to user_root_path }
    end
  end

  def unfollow
    @user = User.find(params[:id])
    current_user.unfollow!(@user)

    respond_to :js
  end


private
  def tweet_params
    params.require(:tweet).permit(:content, :user_id)
  end

  def build_timeline
    return [] unless user_signed_in?
    @tweets = current_user.all_tweets_timeline
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def follow
    @user = User.find(params[:id])
    current_user.follow!(@user)

    respond_to :js
  end

  def unfollow
    @user = User.find(params[:id])
    current_user.unfollow!(@user)

    respond_to :js
  end

  def show
    @user = User.find(params[:id])
  end

  def search
    @search_term = params[:search_term]
    @users = User.basic_search(@search_term)
  end

  def list_followers
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/index.html.erb
<%= render('layouts/jumbotron') %>

app/views/layouts/_dashboard.html.erb
<div class="container-fluid">
  <div class="row">

    <div class="col-md-3">
      <h3>@<%= current_user.handle %> </h3>

    </div>

    <div class="col-md-6">
    </div>

    <div class="col-md-3">
    </div>

  </div> <!-- row -->
</div> <!-- container-fluid -->

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div class="row">
    <div class="col-md-12 error-box">
      <h3>Found the following errors:</h3>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div> <!-- col -->
  </div> <!-- row -->
<% end %>

app/views/layouts/_jumbotron.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Twitter++</h1>
    <p>Like Twitter, but with (1) more character!</p>
    <p>
      <%= link_to "Sign Up!", new_user_registration_path, class: "btn btn-primary btn-lg" %>
      <%= link_to "Or Log In!", new_user_session_path, class: "btn btn-success btn-lg" %>
    </p>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav role="navigation" class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
          <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
          </button>
          <a href="/" class="navbar-brand">Twitter++</a>
      </div>
      <!-- Collection of nav links, forms, and other content for toggling -->
      <div id="navbarCollapse" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
              <li class="dropdown">
                  <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                      <%= current_user ? "@#{current_user.handle}" : "Account" %>
                  <b class="caret"></b></a>
                  <ul role="menu" class="dropdown-menu">
                      <% if user_signed_in? %>
                        <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
                        <li class="divider"></li>
                        <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
                      <% else %>
                        <li><%= link_to 'Create New', new_user_registration_path %></li>
                        <li><%= link_to 'Log In', new_user_session_path %></li>
                      <% end %>
                      <li class="divider"></li>
                  </ul>
              </li>
          </ul>

          <form role="search" class="navbar-form navbar-right" action= <%= tweets_search_path %>>
              <div class="input-group">
                  <input type="text" class="form-control" placeholder="Search Tweets" name="search_term" id="search-term">
                  <div class="input-group-btn">
                      <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                  </div>
              </div>
          </form>

          <form role="search" class="navbar-form navbar-right" action= <%= users_search_path %>>
              <div class="input-group">
                  <input type="text" class="form-control" placeholder="Search Users" name="search_term" id="search-term">
                  <div class="input-group-btn">
                      <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                  </div>
              </div>
          </form>


      </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter++</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container-fluid">
    <%= render('layouts/navbar') %>
  </div>

  <div class="container-fluid">
    <div class="container-fluid">
      <p class="notice flash-msg"><br /><br /><%= flash[:notice] %></p>
      <p class="alert flash-msg"><%= flash[:alert] %></p>
    </div>

    <%= yield %>
  </div>


</body>
</html>

app/views/layouts/dashboard/_dashboard.html.erb
<div class="container-fluid dashboard-div">

  <div class="row dashboard">
    <%= render('layouts/dashboard/left') %>
    <%= render('layouts/dashboard/center') %>
    <%= render('layouts/dashboard/right') %>
    <div class="clearfix visible-md-block"></div>
  </div> <!-- row -->
</div> <!-- container-fluid -->

app/views/layouts/dashboard/_followinglist.html.erb
<div class="dashboard-following-list">
  <p class="lead">Following:</p>
  <ul>
    <% current_user.followed_users.each do |followed| %>
      <li>
        <%= image_tag followed.avatar(:thumb), class: "avatar-image" %>
        <%= link_to "unfollow @#{followed.handle}",
                    timeline_unfollow_user_path(followed),
                      remote: true, class: "btn btn-danger btn-xs" %>
      </li>
    <% end %>
  </ul>
</div>

app/views/layouts/dashboard/_interface.html.erb
<div class="container-fluid dashboard-div">
  <div class="row">

    <div id="dashboard-left-col" class="col-md-3 ui-box">
      <%= render('layouts/dashboard/user_actions') %>
    </div>

    <div id="dashboard-timeline" class="col-md-4 ui-box">
      <%= render('layouts/dashboard/timeline') %>
    </div>

    <div id="dashboard-right-col" class="col-md-3 ui-box">
      <%= render('layouts/dashboard/right') %>
    </div>

    <div class="clearfix visible-md-block"></div>

  </div> <!-- row -->
</div> <!-- container-fluid -->

app/views/layouts/dashboard/_right.html.erb
<%= render('layouts/dashboard/followinglist') %>
<%= render('layouts/dashboard/whotofollow') %>

app/views/layouts/dashboard/_timeline.html.erb
<% if current_user.any_tweets? %>
  <% current_user.all_tweets_timeline.each do |tweet| %>
    <%= render('layouts/dashboard/tweet', tweet: tweet) %>
  <% end %>
<% else %>
  <div id="no-tweets-yet">
    <h3>No tweets yet! :(</h3>
    <p class="text-muted">Pssst: You can fix that by tweeting!</p>
  </div>
<% end %>

app/views/layouts/dashboard/_tweet.html.erb
<% user = User.find(tweet.user_id) %>
<% if current_user.mentioned?(tweet) %>
  <div class="timeline-mention">
<% else %>
  <div class="timeline-tweet">
<% end %>
  <table class="tweet-table">
    <tr>
      <td><%= image_tag user.avatar(:thumb), class: "avatar-image" %></td>
      <td>
        <strong>
          <%= link_to "@#{user.handle}", user_path(user) %>
        </strong> :
        <%= tweet.created_at.to_s %></td>
    </tr>
    <tr>
      <td></td>
      <td class="tweet-table-content"><%= tweet.content %></td>
    </tr>
  </table>
</div>

app/views/layouts/dashboard/_tweetbox.html.erb
<p id="tweet-chars-left">Characters Left: <span class="tweet-chars-left-black">141</span></p>
<%= form_for @tweet, remote: true do |f| %>
  <%= f.text_area :content, cols: 30, rows: 5, autofocus: true %>
  <%= f.submit "Tweet++", class: "btn btn-primary" %>
  <%= f.hidden_field :user_id, value: current_user.id %>
<% end %>

app/views/layouts/dashboard/_user_actions.html.erb
<div class="dashboard-user-stats">
  <%= render('layouts/user/userstats', user: current_user) %>
</div>

<div id="dashboard-tweetbox">
  <%= render('layouts/dashboard/tweetbox') %>
</div>

app/views/layouts/dashboard/_userstats.html.erb
<p class="lead">
  <%= image_tag user.avatar, class: 'avatar-image' %>
  @<%= user.handle %>
</p>
<table class="table">
  <thead>
    <th>Tweets</th>
    <th>Following</th>
    <th>Followers</th>
  </thead>
  <tr>
    <td><%= user.tweets.length %></td>
    <td><%= user.followed_users.length %></td>
    <td><%= user.followers.length %></td>
  </tr>
</table>

app/views/layouts/dashboard/_whotofollow.html.erb
<div class="dashboard-all-users">
  <p class="lead">All Users:</p>
  <ul>
    <% User.all.each do |user| %>
      <% unless user == current_user || current_user.following?(user) %>
        <% if current_user.followed_users.include?(user) %>
          <li>@<%= user.handle %></li>
        <% else %>
          <li>
            <%= image_tag user.avatar(:thumb), class: 'avatar-image' %>
            <%= link_to "follow @#{user.handle}", timeline_follow_user_path(user),
                        remote: true, class: "btn btn-success btn-xs" %>
          </li>
        <% end %>
      <% end %>
    <% end %>
  </ul>
</div>
</div>

app/views/layouts/relations/_followed_users.html.erb
<h3>@<%= user.handle %>'s followers:</h3>
<% user.followers.each do |friend| %>
  <%= render('layouts/relations/usershow', user: friend) %>
<% end %>

app/views/layouts/relations/_following.html.erb
<h3>@<%= user.handle %> is following:</h3>

<% user.followed_users.each do |friend| %>
  <%= render('layouts/relations/usershow', user: friend) %>
<% end %>

app/views/layouts/relations/_usershow.html.erb
<div class="timeline-tweet">
  <table class="usershow-table">
    <tr>
      <td><%= image_tag user.avatar(:thumb), class: "avatar-image" %></td>
      <td>
        <strong>
          <%= link_to "@#{user.handle}", user_path(user) %>
        </strong>
        Member since: <%= user.created_at.to_s %></td>
      </tr>
      <tr>
        <td></td>
        <td class="usershow-bio"><%= user.bio %></td>
      </tr>
      <tr>
        <td></td>
        <td>
        <% if current_user.following?(user) %>
          <%= link_to "unfollow", user_unfollow_path(user), class: "btn btn-xs btn-danger", remote: true %>
        <% else %>
          <%= link_to "follow", user_follow_path(user), class: "btn btn-success btn-xs", remote: true %>
        <% end %>
        </td>
      </tr>
  </table>
</div>

app/views/layouts/user/_follow_button.html.erb
<% unless current_user == user %>
  <% if current_user.following?(user) %>
    <p><%= link_to "unfollow @#{user.handle}", user_unfollow_path(user),
                    remote: true, class: "btn btn-danger" %></p>
  <% else %>
    <p><%= link_to "follow @#{user.handle}", user_follow_path(user),
                remote: true, class: "btn btn-primary" %></p>
  <% end %>
<% end %>

app/views/layouts/user/_user_search_result.html.erb
<table>
  <tr>
    <td><%= image_tag user.avatar(:thumb), class: "avatar-image" %></td>
    <td>
      <strong>
        <%= link_to "@#{user.handle}", user_path(user) %>
      </strong> :
      <span class="text-muted">Joined: <%= user.created_at.to_s %></span>
    </td>
  </tr>
  <tr>
    <td></td>
    <td><%= user.bio %></td>
  </tr>
</table>

app/views/layouts/user/_userstats.html.erb
<p class="lead">
  <% user = current_user if user == nil %>
  <%= image_tag user.avatar(:thumb), class: 'avatar-image' %>
  <%= link_to "@#{user.handle}", user_path(user) %>
</p>
<table class="table">
  <thead>
    <th>Tweets</th>
    <th>Following</th>
    <th>Followers</th>
  </thead>
  <tr>
    <td id="user-tweets-count"><%= link_to user.tweets.count, user_path(user) %></td>
    <td id="user-followed-users-count"><%= link_to user.followed_users.count, user_relations_path(user) %></td>
    <td id="user-followers-count"><%= link_to user.followers.count, user_relations_path(user)  %></td>
  </tr>
</table>

app/views/relations/index.html.erb
<div id="following-index" style="display: none;"></div>
<div class="row">
  <div class="col-md-3 ui-box">
    <div class="dashboard-user-stats">
      <%= render('layouts/user/userstats', user: @user) %>
    </div>
  </div>

  <div id="following-col" class="col-md-3 ui-box">
    <%= render('layouts/relations/following', user: @user) %>
  </div>

  <div id="followed-users-col" class="col-md-3 ui-box">
    <%= render('layouts/relations/followed_users', user: @user) %>
  </div>

  <div class="clearfix visible-md-block"></div>
</div>

app/views/tweets/create.js.erb
$(".dashboard-user-stats").html("<%= j render('layouts/user/userstats', user: current_user) %>");
$("#dashboard-timeline").prepend("<%= j render('layouts/dashboard/tweet', user: current_user, tweet: @tweet) %>");
$("#tweet-chars-left").html("Characters Left: <span class='tweet-chars-left-black'>141</span>");
$('#tweet_content').val('');
$("#tweet_content").focus();
$("#no-tweets-yet").remove();

app/views/tweets/follow.js.erb
$(".dashboard-user-stats").html("<%= j render('layouts/user/userstats', user: current_user) %>");

if ($("#dashboard-timeline").length) {
  $("#dashboard-right-col").html("<%= j render('layouts/dashboard/right') %>");
  $("#dashboard-timeline").html("<%= j render('layouts/dashboard/timeline') %>");
}

app/views/tweets/index.html.erb
<%= render('layouts/errors', object: @tweet) %>
<%= render('layouts/dashboard/interface') %>

app/views/tweets/search.html.erb
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6 ui-box">
    <h3>Tweet Search Results</h3>
    <p class="text-muted">query: <%= @search_term %></p>

    <% @tweets.each do |tweet| %>
      <% if current_user.mentions.find_by(user_id: current_user.id,
                                          tweet_id: tweet.id) %>
        <div class="timeline-mention">
          <%= render( 'layouts/dashboard/tweet',
                      user: User.find(tweet.user_id), tweet: tweet) %>
        </div>
      <% else %>
        <div class="timeline-tweet">
          <%= render('layouts/dashboard/tweet', user: User.find(tweet.user_id), tweet: tweet) %>
        </div>
      <% end %>
    <% end %>

    <%= link_to "Back to Timeline", user_root_path, class: "btn btn-primary" %>
  </div>

  <div class="col-md-3"></div>
  <div class="clearfix visible-md-block"></div>
</div>

app/views/tweets/unfollow.js.erb
$(".dashboard-user-stats").html("<%= j render('layouts/user/userstats', user: current_user) %>");
$("#dashboard-right-col").html("<%= j render('layouts/dashboard/right') %>");
$("#dashboard-timeline").html("<%= j render('layouts/dashboard/timeline') %>");

app/views/users/follow.js.erb
$("#follow-unfollow-button").html("<%= j render('layouts/user/follow_button', user: @user) %>");
$("#dashboard-user-stats").html("<%= j render('layouts/user/userstats', user: @user)  %>");

if ($("#following-col").length) {
  <% @user = current_user %>
  $("#following-col").html("<%= j render('layouts/relations/following', user: @user ) %>");
  $("#followed-users-col").html("<%= j render('layouts/relations/followed_users', user: @user ) %>");
}

app/views/users/search.html.erb
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6 ui-box">
    <h3>User Search Results</h3>
    <p class="text-muted">query: <%= @search_term %></p>

    <% @users.each do |user| %>
      <div class="timeline-tweet">
        <%= render('layouts/user/user_search_result', user: user) %>
      </div>
    <% end %>

    <% if @users.length == 0 %>
      <div class="timeline-mention">
        <h3>--NO RESULTS--</h3>
      </div>
    <% end %>

    <%= link_to "Back to Timeline", user_root_path, class: "btn btn-primary" %>
  </div>

  <div class="col-md-3"></div>
  <div class="clearfix visible-md-block"></div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-3 ui-box">
    <div class="dashboard-user-stats">
      <%= render('layouts/user/userstats', user: @user) %>
    </div>
  </div>

  <div class="col-md-4 ui-box">
    <% if !@user.any_tweets? %>
      <h3>@<%= @user.handle %> has no tweets yet</h3>
    <% else %>
      <% @user.tweets.each do |tweet| %>
        <%= render('layouts/dashboard/tweet', tweet: tweet) %>
      <% end %>
    <% end %>
  </div>

  <div class="col-md-3 ui-box">
    <%= image_tag @user.avatar(:medium), class: "avatar-image" %>
    <h3>@<%= @user.handle %>'s bio:</h3>
    <p><%= @user.bio %></p>
    <div id="follow-unfollow-button">
      <%= render('layouts/user/follow_button', user: @user) %>
    </div>
  </div>

  <div class="clearfix visible-md-block"></div>
</div>

app/views/users/unfollow.js.erb
$("#follow-unfollow-button").html("<%= j render('layouts/user/follow_button', user: @user) %>");
$("#dashboard-user-stats").html("<%= j render('layouts/user/userstats', user: @user)  %>");

if ($("#following-col").length) {
  <% @user = current_user %>
  $("#following-col").html("<%= j render('layouts/relations/following', user: @user ) %>");
  $("#followed-users-col").html("<%= j render('layouts/relations/followed_users', user: @user) %>");
}